### ISSUE TITLE
japan-train-data

### ISSUE THREAD

**Issue by adieuadieu** [piuccio/open-data-jp-railway-lines#1]
Dunno if it helps, but I've done a similar thing with [this repository](https://github.com/adieuadieu/japan-train-data) but I ran many of the station/train line names through Google Translate (mixed results, as you might expect).

**Comment by piuccio** [comment]
Wonderful, I'll have a look and try to integrate the two

**Comment by piuccio** [comment]
Thanks, had a look at your project and ended up splitting up this project in two.
https://github.com/piuccio/wikipedia-jp-railway-lines has a list of railways extracted from wikipedia and their English name. I used your repo to fill in some gaps. Some lines still don't have translations, but any correction goes there

**Comment by adieuadieu** [comment]
Nice!
